### ISSUE TITLE
crashes when Nonetype is passed as image

### ISSUE THREAD

**Issue by txoof** [txoof/epdlib#10]
Screen.py 

line 253: `self.buffer_no_image = self._epd.getbuffer(Image.new('L', self.resolution, 255))`

line 291: `self.buffer_no_image = self.epd.getbuffer(Image.new('L', self.resolution, 255))`

line 382: `image_buffer = epd.getbuffer(image)` <--- this is likely the culprit of the crash

```
Dec  9 22:12:21 paperpi paperpi[949]: [950] Failed to execute script paperpi
Dec  9 22:12:21 paperpi paperpi[949]: Traceback (most recent call last):
Dec  9 22:12:21 paperpi paperpi[949]:   File "paperpi/paperpi.py", line 568, in <module>
Dec  9 22:12:21 paperpi paperpi[949]:   File "paperpi/paperpi.py", line 551, in main
Dec  9 22:12:21 paperpi paperpi[949]:   File "paperpi/paperpi.py", line 428, in update_loop
Dec  9 22:12:21 paperpi paperpi[949]:   File "epdlib/Screen.py", line 388, in writeEPD
Dec  9 22:12:21 paperpi paperpi[949]:   File "/tmp/_MEI3ExySM/waveshare_epd/epd7in5_V2.py", line 118, in getbuffer
Dec  9 22:12:21 paperpi paperpi[949]:     image_monocolor = image.convert('1')
Dec  9 22:12:21 paperpi paperpi[949]: AttributeError: 'NoneType' object has no attribute 'convert'
Dec  9 22:12:22 paperpi systemd[1]: paperpi-daemon.service: Main process exited, code=exited, status=255/EXCEPTION
```

**Comment by txoof** [comment]
wrap line 382 in `try:`
