### ISSUE TITLE
crash when img is None in Screen.writeEPD

### ISSUE THREAD

**Issue by txoof** [txoof/epdlib#17]
Traceback (most recent call last):
  File "paperpi/paperpi.py", line 648, in <module>
  File "paperpi/paperpi.py", line 631, in main
  File "paperpi/paperpi.py", line 469, in update_loop
  File "epdlib/Screen.py", line 273, in wrapper
  File "epdlib/Screen.py", line 535, in writeEPD
AttributeError: 'NoneType' object has no attribute 'rotate'

**Comment by txoof** [comment]
resolved
